# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › https://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Calcutta
 
# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Samir Paul # the main title

tagline: The Blog of a Lifelong Learner # it will display as the sub-title

description: >- # used by seo meta and the atom feed
  Technical blog for developers. Computer Science, Data Structures Algorithms, Networking, Artificial Intelligence and Coding Interview Prep.

# Fill in the protocol & hostname for your site.
# e.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://samirpaulb.github.io"

github:
  username: SamirPaulb # change to your github username

twitter:
  username: SamirPaulb # change to your twitter username
  card: summary_large_image

facebook:
  app_id: 6800281970014175
  publisher: 
  admins: 

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Samir Paul
  email: fktjagtmn@mozmail.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - /index.html
    - https://twitter.com/SamirPaulb # change to your twitter homepage
    - https://github.com/SamirPaulb # change to your github homepage
    - https://www.linkedin.com/in/SamirPaul
    - https://www.facebook.com/SamirPaulb
    - https://www.instagram.com/SamirPaulb
    - https://www.youtube.com/SamirPaulb

google_site_verification: vJAOBxbJTCK2vXG-hLFeGsoC9hXgFlCpuJJ8AcJLROQ

webmaster_verifications:
  google: vJAOBxbJTCK2vXG-hLFeGsoC9hXgFlCpuJJ8AcJLROQ
  bing: 1A92FC2EC113F8616A21D76DA684A133
  yandex: fe6a06c57be84984
  pinterest: 24bac6e1fbf1750de40d59bb788d9dd9
  facebook: 3pkgruuk3kzlsn3jdfehgbd4sem1qb

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

google_analytics:
  id: G-CP4QE6ZEV0

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode: # [light|dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn: https://spcdn.pages.dev

# the avatar on sidebar, support local or CORS resources
avatar: /assets/img/avatar.webp

# boolean type, the global switch for TOC in posts.
toc: true

future: true

comments:
  active: disqus 
  # The active options are as follows:
  disqus:
    shortname: samirpaul
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: # SamirPaul1/comments
    repo_id: # R_kgDOIMPz0Q
    category: # General
    category_id: # DIC_kwDOIMPz0c4CR7E4
    mapping: # pathname
    input_position: # top
    lang: # en
    loading: # 'lazy'
    reactions_enabled: # 1 # optional, default to the value of `1`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: true 
    env: # [development|production]

pwa:
  enabled: true # the option for PWA feature

paginate: 10

# The base URL of your site
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

